version: '2'
services:
  postgres:
    container_name: postgres_pci
    image: postgres:9.4
    ports:
    - 5433:5432
    environment:
    - POSTGRES_USER=pci
    - POSTGRES_PASSWORD=pci
    volumes:
    - /var/lib/hotelgenius/pci/postgresql/data/pgdata:/var/lib/postgresql/data
    networks:
    - pci_net
  pci:
    container_name: pci
    image: hotelgeniusproduction/hotelgenius-pci
    ports:
    - 8081:8080
    - 5004:5004
    environment:
    - PCI_SERVER_PORT=8080
    - PCI_DB_HOST=postgres
    - PCI_DB_PORT=5432
    depends_on:
    - postgres
    env_file:
    - dev.env
    networks:
    - pci_net
networks:
  pci_net:
    driver: bridge